################################################################################
# general
################################################################################

- platform: knx
  name: blinds_shadow_all
  address:       '0/1/4'

- platform: knx
  name: blinds_shadow_groundfloor
  address:       '0/1/14'

- platform: knx
  name: blinds_shadow_upperfloor
  address:       '0/1/24'

################################################################################
# basement
################################################################################

- platform: knx
  name: utility_ceiling
  address:       '1/0/0'
  state_address: '1/7/0'

- platform: knx
  name: storage_ceiling
  address:       '1/0/5'
  state_address: '1/7/5'

- platform: knx
  name: corridor1_ceiling
  address:       '1/0/10'
  state_address: '1/7/10'

- platform: knx
  name: workshop_ceiling
  address:       '1/0/15'
  state_address: '1/7/15'

- platform: knx
  name: driveway_ceiling
  address:       '1/0/20'
  state_address: '1/7/20'

- platform: knx
  name: garage_ceiling
  address:       '1/0/25'
  state_address: '1/7/25'

  # ----- PIR
- platform: knx
  name: utility_pir
  address:       '1/0/4'
  state_address: '1/7/4'

- platform: knx
  name: storage_pir
  address:       '1/0/9'
  state_address: '1/7/9'

- platform: knx
  name: corridor1_pir
  address:       '1/0/14'
  state_address: '1/7/14'

- platform: knx
  name: workshop_pir
  address:       '1/0/19'
  state_address: '1/7/19'

- platform: knx
  name: driveway_pir
  address:       '1/0/24'
  state_address: '1/7/24'

- platform: knx
  name: garage_pir
  address:       '1/0/29'
  state_address: '1/7/29'

################################################################################
# ground floor
################################################################################

# 2/0/110 for lower and upper
- platform: knx
  name: kitchen_lower
  address: '2/0/5'
  state_address: '2/7/5'

- platform: knx
  name: kitchen_upper
  address: '2/0/10'
  state_address: '2/7/10'

# 2/0/15 kitchen ceiling (dali)
# 2/0/20 kitchen offtake (dali)

- platform: knx
  name: livingroom_ceiling
  address: '2/0/25'
  state_address: '2/7/25'

- platform: knx
  name: livingroom_socket2
  address: '2/0/30'
  state_address: '2/7/30'

- platform: knx
  name: livingroom_socket3
  address: '2/0/35'
  state_address: '2/7/35'

- platform: knx
  name: livingroom_socket4
  address: '2/0/40'
  state_address: '2/7/40'

# 2/0/45 dining ceiling
# 2/0/50 living wall

- platform: knx
  name: facade_light_south
  address: '2/0/55'
  state_address: '2/7/55'

- platform: knx
  name: facade_light_west
  address: '2/0/60'
  state_address: '2/7/60'

- platform: knx
  name: guest_socket
  address: '2/0/65'
  state_address: '2/7/65'

# 2/0/70 guest ceiling (dali)
# 2/0/{75,80,85} not in use
# 2/0/90 corridor ceiling (dail)
# 2/0/95 corridor trigger

- platform: knx
  name: restroom_ceiling
  address: '2/0/100'
  state_address: '2/7/100'

# 2/0/105 entrance (dali)
- platform: knx
  name: kitchen_lowerupper
  address: '2/0/110'
  state_address: '2/7/110'

  #--- PIR

- platform: knx
  name: livinroom_pir
  address: '2/0/29'
  state_address: '2/7/29'

- platform: knx
  name: facade_pir_south
  address: '2/0/59'
  state_address: '2/7/59'

- platform: knx
  name: facade_pir_west
  address: '2/0/64'
  state_address: '2/7/64'

- platform: knx
  name: guest_pir
  address: '2/0/74'
  state_address: '2/7/74'

- platform: knx
  name: corridor2_pir_ceiling
  address: '2/0/93'
  state_address: '2/7/93'

- platform: knx
  name: corridor2_pir_wall
  address: '2/0/94'
  state_address: '2/7/94'

- platform: knx
  name: restroom_pir
  address: '2/0/104'
  state_address: '2/7/104'

- platform: knx
  name: entrance_pir
  address: '2/0/109'
  state_address: '2/7/109'

################################################################################
# upper floor
################################################################################

- platform: knx
  name: bedroom_ceiling
  address:       '3/0/0'
  state_address: '2/7/0'

- platform: knx
  name: bedroom_socket1
  address:       '3/0/5'
  state_address: '3/7/5'

- platform: knx
  name: bedroom_socket_left
  address:       '3/0/10'
  state_address: '3/7/10'

- platform: knx
  name: bedroom_socket_right
  address:       '3/0/15'
  state_address: '3/7/15'

- platform: knx
  name: bathroom_mirror
  address:       '3/0/30'
  state_address: '3/7/30'

- platform: knx
  name: child_ceiling
  address:       '3/0/50'
  state_address: '3/7/50'

- platform: knx
  name: child_socket
  address:       '3/0/55'
  state_address: '3/7/55'

- platform: knx
  name: multimedia_ceiling
  address:       '3/0/60'
  state_address: '3/7/60'

- platform: knx
  name: multimedia_socket
  address:       '3/0/65'
  state_address: '3/7/65'

- platform: knx
  name: bathroom_socket
  address:       '3/2/30'
  state_address: '3/2/31'

  #--- PIR

- platform: knx
  name: bedroom_pir_ceiling
  address:       '3/0/04'
  state_address: '3/7/04'

- platform: knx
  name: bedroom_pir_wall
  address:       '3/0/24'
  state_address: '3/7/24'

- platform: knx
  name: dresser_pir
  address:       '3/0/29'
  state_address: '3/7/29'

- platform: knx
  name: bathroom_pir
  address:       '3/0/39'
  state_address: '3/7/39'

- platform: knx
  name: corridor3_pir
  address:       '3/0/44'
  state_address: '3/7/44'

- platform: knx
  name: child_pir
  address:       '3/0/54'
  state_address: '3/7/54'

- platform: knx
  name: multimedia_pir
  address:       '3/0/64'
  state_address: '3/7/64'


