- platform: luxtronik
  scan_interval: 60
  sensors:
    - id: ID_WEB_Temperatur_TVL
      friendly_name: Temperatur Vorlauf
    - id: ID_WEB_Temperatur_TRL
      friendly_name: Temperatur Rücklauf
    - id: ID_WEB_Temperatur_THG
      friendly_name: Temperatur Heissgas
    - id: ID_WEB_Temperatur_TA
      friendly_name: Temperatur Aussen
    - id: ID_WEB_Temperatur_TBW
      friendly_name: Temperatur Warmwasser
    - id: ID_WEB_Temperatur_TWE
      friendly_name: Temperatur Sole Ein
    - id: ID_WEB_Temperatur_TWA
      friendly_name: Temperatur Sole Aus
    - id: ID_WEB_Zaehler_BetrZeitVD1
      friendly_name: Betriebsstunden Verdichter 1
    - id: ID_WEB_Zaehler_BetrZeitVD2
      friendly_name: Betriebsstunden Verdichter 2
    - id: ID_WEB_Zaehler_BetrZeitWP
      friendly_name: Betriebsstunden Waermepumpe
    - id: ID_WEB_Zaehler_BetrZeitHz
      friendly_name: Betriebsstunden Heizung
    - id: ID_WEB_Zaehler_BetrZeitBW
      friendly_name: Betriebsstunden Warmwasser
    - id: ID_WEB_HauptMenuStatus_Zeile1
      friendly_name: Status1
    - id: ID_WEB_HauptMenuStatus_Zeile2
      friendly_name: Status2
    - id: ID_WEB_HauptMenuStatus_Zeile3
      friendly_name: Status3
    - id: ID_WEB_WMZ_Heizung
      friendly_name: WMHz

