- platform: knx
  name: workshop_temp
  temperature_address: '1/2/0'
  target_temperature_address: '1/2/1'
  target_temperature_state_address: '1/2/1'
  setpoint_shift_address: '1/2/2'
  operation_mode_address: '1/2/3'
  operation_mode_frost_protection_address: '1/2/7'
  operation_mode_night_address: '1/2/7'
  operation_mode_comfort_address: '1/2/5'
  operation_mode_state_address: '1/2/9'
  min_temp: 12.0
  max_temp: 26.0

- platform: knx
  name: livingroom_temp
  temperature_address: '2/2/0'
  target_temperature_address: '2/2/1'
  target_temperature_state_address: '2/2/1'
  setpoint_shift_address: '2/2/2'
  operation_mode_address: '2/2/3'
  min_temp: 12.0
  max_temp: 26.0

- platform: knx
  name: guest_temp
  temperature_address: '2/2/5'
  target_temperature_address: '2/2/6'
  target_temperature_state_address: '2/2/6'
  setpoint_shift_address: '2/2/7'
  operation_mode_address: '2/2/8'
  min_temp: 12.0
  max_temp: 26.0

- platform: knx
  name: bedroom_temp
  temperature_address: '3/2/0'
  target_temperature_address: '3/2/1'
  target_temperature_state_address: '3/2/1'
  setpoint_shift_address: '3/2/2'
  operation_mode_address: '3/2/3'
  min_temp: 12.0
  max_temp: 26.0

- platform: knx
  name: child_temp
  temperature_address: '3/2/5'
  target_temperature_address: '3/2/6'
  target_temperature_state_address: '3/2/6'
  setpoint_shift_address: '3/2/7'
  operation_mode_address: '3/2/8'
  min_temp: 12.0
  max_temp: 26.0

- platform: knx
  name: multimedia_temp
  temperature_address: '3/2/10'
  target_temperature_address: '3/2/11'
  target_temperature_state_address: '3/2/11'
  setpoint_shift_address: '3/2/12'
  operation_mode_address: '3/2/13'
  min_temp: 12.0
  max_temp: 26.0

